// <auto-generated />
namespace OganiShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Databaseas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Databaseas));
        
        string IMigrationMetadata.Id
        {
            get { return "202205040257153_Databaseas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
