// <auto-generated />
namespace OganiShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddE));
        
        string IMigrationMetadata.Id
        {
            get { return "202205010914198_AddE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
